# Generated by Django 2.2.1 on 2019-09-26 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='totalAssists',
            new_name='totalAttendances',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='totalAssists',
            new_name='totalAttendances',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='sport',
            field=models.CharField(choices=[('AT', 'Atletismo'), ('BB', 'Basketball'), ('ES', 'ESports'), ('FB', 'Futbol'), ('HB', 'Handball'), ('TN', 'Tennis'), ('PP', 'Ping pong'), ('TA', 'Tiro con arco'), ('TC', 'Tochito'), ('VB', 'Voleibol')], default='FB', max_length=2),
        ),
        migrations.CreateModel(
            name='CallTheRollTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('idTeamTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
