# Generated by Django 2.2.5 on 2019-10-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191001_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsmember',
            name='expediente',
            field=models.IntegerField(default=242424),
            preserve_default=False,
        ),
    ]
