# Generated by Django 2.2.5 on 2019-10-29 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Varonil', 'Varonil'), ('Femenil', 'Femenil')], default='Varonil', max_length=7, verbose_name='Rama')),
                ('sport', models.CharField(choices=[('Atletismo', 'Atletismo'), ('Basketball', 'Basketball'), ('eSports', 'ESports'), ('Futbol', 'Futbol'), ('Handball', 'Handball'), ('Tennis', 'Tennis'), ('Ping-Pong', 'Ping pong'), ('Tiro con arco', 'Tiro con arco'), ('Tochito', 'Tochito'), ('Voleibol', 'Voleibol')], default='Futbol', max_length=15, verbose_name='Deporte')),
                ('schedule', models.CharField(blank=True, max_length=50, verbose_name='Horario')),
                ('totalAttendances', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total Asistencias')),
                ('period', models.CharField(blank=True, max_length=6, null=True, verbose_name='Periodo')),
                ('maxMembers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de estudiantes')),
                ('totalMembers', models.PositiveIntegerField(blank=True, default=0, verbose_name='Total de estudiantes')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taller deportivo',
                'verbose_name_plural': 'Talleres deportivos',
            },
        ),
        migrations.CreateModel(
            name='WsMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.IntegerField()),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo')),
                ('plan', models.CharField(choices=[('SOF11', 'SOF11'), ('LAT11', 'LAT11'), ('INF11', 'INF11'), ('INC11', 'INC11'), ('TEL11', 'TEL11'), ('SOF18', 'SOF18'), ('LAT18', 'LAT18'), ('INF18', 'INF18'), ('INC18', 'INC18'), ('TEL18', 'TEL18')], default='SOF11', max_length=5)),
                ('group', models.SmallIntegerField(choices=[(60, '60'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74')], default=70)),
                ('totalAttendances', models.SmallIntegerField(blank=True, null=True, verbose_name='Total asistencias')),
                ('absolved', models.BooleanField(blank=True, default=False, verbose_name='Absuelto')),
                ('idWs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Workshop')),
            ],
            options={
                'verbose_name': 'Miembro de taller',
                'verbose_name_plural': 'Miembros de taller',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idWs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='CallTheRollWs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('idSesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Sesion')),
                ('idWsMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.WsMember')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
