# Generated by Django 2.2.1 on 2019-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltherollws',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
