# Generated by Django 2.2.1 on 2019-11-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltherollws',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Asistió'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='date',
            field=models.DateField(verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='wsmember',
            name='group',
            field=models.SmallIntegerField(choices=[(60, '60'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74')], default=70, verbose_name='Grupo'),
        ),
    ]
