# Generated by Django 2.2.5 on 2019-11-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20191115_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='sport',
            field=models.CharField(choices=[('Atletismo', 'Atletismo'), ('Basketball', 'Basketball'), ('eSports', 'ESports'), ('Futbol', 'Futbol'), ('Handball', 'Handball'), ('Tenis', 'Tenis'), ('Ping-Pong', 'Ping pong'), ('Tiro con arco', 'Tiro con arco'), ('Tochito', 'Tochito'), ('Voleibol', 'Voleibol')], default='Futbol', max_length=15, verbose_name='Deporte'),
        ),
    ]
