# Generated by Django 2.2.1 on 2019-10-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20191016_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltherollws',
            name='idWs',
        ),
    ]
