# Generated by Django 2.2.5 on 2019-12-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20191128_0840'),
        ('workshop', '0003_auto_20191129_1125'),
    ]

    operations = [
    ]
