# Generated by Django 2.2.1 on 2019-10-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_calltherollws_idws'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsmember',
            name='plan',
            field=models.CharField(choices=[('SOF11', 'SOF11'), ('LAT11', 'LAT11'), ('INF11', 'INF11'), ('INC11', 'INC11'), ('TEL11', 'TEL11'), ('SOF18', 'SOF18'), ('LAT18', 'LAT18'), ('INF18', 'INF18'), ('INC18', 'INC18'), ('TEL18', 'TEL18')], default='SOF11', max_length=5),
        ),
    ]
