# Generated by Django 2.2.7 on 2019-12-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_merge_20191203_0923'),
        ('workshop', '0004_merge_20191203_0928'),
    ]

    operations = [
    ]
