# Generated by Django 2.2.1 on 2019-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_wsmember_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsmember',
            name='group',
            field=models.SmallIntegerField(choices=[(60, '60'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74')], default=70),
        ),
    ]
