# Generated by Django 2.2.1 on 2019-10-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_wsmember_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltherollws',
            old_name='idUser',
            new_name='idWsMember',
        ),
        migrations.RenameField(
            model_name='wsmember',
            old_name='totalAssists',
            new_name='totalAttendances',
        ),
        migrations.RemoveField(
            model_name='calltherollws',
            name='date',
        ),
        migrations.AddField(
            model_name='workshop',
            name='totalMembers',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Total de estudiantes'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('idWs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='calltherollws',
            name='idSesion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workshop.Sesion'),
            preserve_default=False,
        ),
    ]
