# Generated by Django 2.2.7 on 2019-12-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_merge_20191203_2014'),
        ('workshop', '0005_merge_20191205_1054'),
    ]

    operations = [
    ]
