# Generated by Django 2.2.1 on 2019-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_auto_20191027_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='date',
            field=models.DateField(),
        ),
    ]
