# Generated by Django 2.2.1 on 2019-10-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wsmember_expediente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltherollteam',
            old_name='idTeamTeam',
            new_name='idTeam',
        ),
        migrations.AddField(
            model_name='teammember',
            name='expediente',
            field=models.IntegerField(default=242798),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='maxMembers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de estudiantes'),
        ),
        migrations.AddField(
            model_name='wsmember',
            name='absolved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Absuelto'),
        ),
        migrations.AlterField(
            model_name='calltherollteam',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TeamMember'),
        ),
        migrations.CreateModel(
            name='CallTheRollWs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WsMember')),
                ('idWs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop')),
            ],
        ),
    ]
