# Generated by Django 2.2.1 on 2019-10-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191007_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltherollws',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='calltherollws',
            name='idWs',
        ),
        migrations.RemoveField(
            model_name='match',
            name='idTeam',
        ),
        migrations.RemoveField(
            model_name='player',
            name='idMatch',
        ),
        migrations.RemoveField(
            model_name='player',
            name='idTeamMember',
        ),
        migrations.RemoveField(
            model_name='team',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='idTeam',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='wsmember',
            name='idWS',
        ),
        migrations.DeleteModel(
            name='CallTheRollTeam',
        ),
        migrations.DeleteModel(
            name='CallTheRollWs',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
        migrations.DeleteModel(
            name='WsMember',
        ),
    ]
