# Generated by Django 2.2.1 on 2019-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltherollteam',
            name='idTeam',
        ),
        migrations.AlterField(
            model_name='match',
            name='rival',
            field=models.CharField(choices=[('FBA', 'Bellas Artes'), ('FCP', 'Ciencias Políticas y Sociales'), ('FCA', 'Contaduría y Administración'), ('FDE', 'Derecho'), ('FEN', 'Enfermería'), ('FFI', 'Filosofía'), ('FIN', 'Ingeniería'), ('FLL', 'Lenguas y Letras'), ('FME', 'Medicina'), ('FPS', 'Psicología'), ('FQU', 'Química')], max_length=3),
        ),
    ]
