# Generated by Django 2.2.7 on 2019-11-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20191115_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winned',
            field=models.BooleanField(default=False, null=True, verbose_name='¿Se ganó?'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('Atletismo', 'Atletismo'), ('Basketball', 'Basketball'), ('eSports', 'ESports'), ('Futbol', 'Futbol'), ('Handball', 'Handball'), ('Tenis', 'Tenis'), ('Ping-Pong', 'Ping pong'), ('Tiro con arco', 'Tiro con arco'), ('Tochito', 'Tochito'), ('Voleibol', 'Voleibol')], max_length=15, verbose_name='Deporte'),
        ),
    ]
