# Generated by Django 2.2.7 on 2019-11-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191123_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Día'),
        ),
    ]
