# Generated by Django 2.2.7 on 2019-12-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20191129_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winned',
            field=models.SmallIntegerField(choices=[('FBA', 'Bellas Artes'), ('FCP', 'Ciencias Políticas y Sociales'), ('FCA', 'Contaduría y Administración'), ('FDE', 'Derecho'), ('FEN', 'Enfermería'), ('FFI', 'Filosofía'), ('FIN', 'Ingeniería'), ('FLL', 'Lenguas y Letras'), ('FME', 'Medicina'), ('FPS', 'Psicología'), ('FQU', 'Química')], null=True, verbose_name='¿Se ganó?'),
        ),
    ]
