# Generated by Django 2.2.7 on 2019-12-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20191201_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winned',
            field=models.SmallIntegerField(choices=[(1, 'Se ganó'), (0, 'Se perdió'), (2, 'Empate')], null=True, verbose_name='¿Se ganó?'),
        ),
    ]
