# Generated by Django 2.2.7 on 2019-12-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20191201_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='idMatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_players', to='team.Match'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='idTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_members', to='team.Team'),
        ),
    ]
